on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run linksafe
        uses: TechWiz-3/linksafe@main
        with:
          dirs: ".,./addons,./docs,./other"
          verbose: true
          whitelist_files: "./docs/index.html"
